const { normalizeLanguage } = require('./locale');

/** English catalog labels from fitness seed data — keys must match DB/route names. */
const FITNESS_LABELS_EN = {
  Yoga: 'Yoga',
  Meditation: 'Meditation',
  Cardio: 'Cardio',
  Stretching: 'Stretching',
  'Healthy Diet': 'Healthy Diet',
  'Beginner Yoga Flow': 'Beginner Yoga Flow',
  'Yoga for Anxiety Relief': 'Yoga for Anxiety Relief',
  'Bedtime Yoga': 'Bedtime Yoga',
  '5-Minute Daily Meditation': '5-Minute Daily Meditation',
  'Sleep Meditation': 'Sleep Meditation',
  'Anxiety-Calming Breath': 'Anxiety-Calming Breath',
  'Low Impact Cardio': 'Low Impact Cardio',
  'Beginner HIIT': 'Beginner HIIT',
  'Full Body Stretch': 'Full Body Stretch',
  'Morning Stretch': 'Morning Stretch',
  'Healthy Breakfast Ideas': 'Healthy Breakfast Ideas',
  'Meal Prep Basics': 'Meal Prep Basics',
  '10-Minute Beginner Yoga': '10-Minute Beginner Yoga',
  'Gentle Morning Yoga': 'Gentle Morning Yoga',
  'Yoga for Anxiety and Stress': 'Yoga for Anxiety and Stress',
  'Calming Yoga for Worry': 'Calming Yoga for Worry',
  'Bedtime Yoga for Relaxation': 'Bedtime Yoga for Relaxation',
  'Quick Reset Meditation': 'Quick Reset Meditation',
  'Deep Sleep Talk Down': 'Deep Sleep Talk Down',
  'Breathing for Anxiety Relief': 'Breathing for Anxiety Relief',
  'Low Impact Cardio Workout': 'Low Impact Cardio Workout',
  'Beginner HIIT Session': 'Beginner HIIT Session',
  'Full Body Stretch Routine': 'Full Body Stretch Routine',
  '5-Minute Morning Stretch': '5-Minute Morning Stretch',
  '3 Healthy Breakfast Ideas': '3 Healthy Breakfast Ideas',
  'Beginner Meal Prep Guide': 'Beginner Meal Prep Guide',
};

const FITNESS_LABELS = {
  hi: {
    Yoga: 'योग',
    Meditation: 'ध्यान',
    Cardio: 'कार्डियो',
    Stretching: 'स्ट्रेचिंग',
    'Healthy Diet': 'स्वस्थ आहार',
    'Beginner Yoga Flow': 'शुरुआती योग फ्लो',
    'Yoga for Anxiety Relief': 'चिंता राहत के लिए योग',
    'Bedtime Yoga': 'सोने से पहले योग',
    '5-Minute Daily Meditation': '5-मिनट दैनिक ध्यान',
    'Sleep Meditation': 'नींद ध्यान',
    'Anxiety-Calming Breath': 'चिंता-शांत श्वास',
    'Low Impact Cardio': 'कम प्रभाव कार्डियो',
    'Beginner HIIT': 'शुरुआती HIIT',
    'Full Body Stretch': 'पूरे शरीर की स्ट्रेच',
    'Morning Stretch': 'सुबह की स्ट्रेच',
    'Healthy Breakfast Ideas': 'स्वस्थ नाश्ते के विचार',
    'Meal Prep Basics': 'भोजन तैयारी की मूल बातें',
    '10-Minute Beginner Yoga': '10-मिनट शुरुआती योग',
    'Gentle Morning Yoga': 'हल्का सुबह योग',
    'Yoga for Anxiety and Stress': 'चिंता और तनाव के लिए योग',
    'Calming Yoga for Worry': 'चिंता के लिए शांत योग',
    'Bedtime Yoga for Relaxation': 'आराम के लिए सोने से पहले योग',
    'Quick Reset Meditation': 'त्वरित रीसेट ध्यान',
    'Deep Sleep Talk Down': 'गहरी नींद मार्गदर्शन',
    'Breathing for Anxiety Relief': 'चिंता राहत श्वास',
    'Low Impact Cardio Workout': 'कम प्रभाव कार्डियो वर्कआउट',
    'Beginner HIIT Session': 'शुरुआती HIIT सत्र',
    'Full Body Stretch Routine': 'पूरे शरीर स्ट्रेच दिनचर्या',
    '5-Minute Morning Stretch': '5-मिनट सुबह स्ट्रेच',
    '3 Healthy Breakfast Ideas': '3 स्वस्थ नाश्ते के विचार',
    'Beginner Meal Prep Guide': 'शुरुआती भोजन तैयारी गाइड',
  },
  pa: {
    Yoga: 'ਯੋਗ',
    Meditation: 'ਧਿਆਨ',
    Cardio: 'ਕਾਰਡੀਓ',
    Stretching: 'ਸਟ੍ਰੈਚਿੰਗ',
    'Healthy Diet': 'ਸਿਹਤਮੰਦ ਖੁਰਾਕ',
    'Beginner Yoga Flow': 'ਸ਼ੁਰੂਆਤੀ ਯੋਗ ਫਲੋ',
    'Yoga for Anxiety Relief': 'ਚਿੰਤਾ ਰਾਹਤ ਲਈ ਯੋਗ',
    'Bedtime Yoga': 'ਸੌਣ ਤੋਂ ਪਹਿਲਾਂ ਯੋਗ',
    '5-Minute Daily Meditation': '5-ਮਿੰਟ ਰੋਜ਼ਾਨਾ ਧਿਆਨ',
    'Sleep Meditation': 'ਨੀਂਦ ਧਿਆਨ',
    'Anxiety-Calming Breath': 'ਚਿੰਤਾ-ਸ਼ਾਂਤ ਸਾਹ',
    'Low Impact Cardio': 'ਘੱਟ ਪ੍ਰਭਾਵ ਕਾਰਡੀਓ',
    'Beginner HIIT': 'ਸ਼ੁਰੂਆਤੀ HIIT',
    'Full Body Stretch': 'ਪੂਰੇ ਸਰੀਰ ਦੀ ਸਟ੍ਰੈਚ',
    'Morning Stretch': 'ਸਵੇਰ ਦੀ ਸਟ੍ਰੈਚ',
    'Healthy Breakfast Ideas': 'ਸਿਹਤਮੰਦ ਨਾਸ਼ਤੇ ਦੇ ਵਿਚਾਰ',
    'Meal Prep Basics': 'ਭੋਜਨ ਤਿਆਰੀ ਦੀ ਬੁਨਿਆਦ',
    '10-Minute Beginner Yoga': '10-ਮਿੰਟ ਸ਼ੁਰੂਆਤੀ ਯੋਗ',
    'Gentle Morning Yoga': 'ਹਲਕਾ ਸਵੇਰ ਯੋਗ',
    'Yoga for Anxiety and Stress': 'ਚਿੰਤਾ ਅਤੇ ਤਣਾਅ ਲਈ ਯੋਗ',
    'Calming Yoga for Worry': 'ਚਿੰਤਾ ਲਈ ਸ਼ਾਂਤ ਯੋਗ',
    'Bedtime Yoga for Relaxation': 'ਆਰਾਮ ਲਈ ਸੌਣ ਤੋਂ ਪਹਿਲਾਂ ਯੋਗ',
    'Quick Reset Meditation': 'ਤੁਰੰਤ ਰੀਸੈੱਟ ਧਿਆਨ',
    'Deep Sleep Talk Down': 'ਡੂੰਘੀ ਨੀਂਦ ਮਾਰਗਦਰਸ਼ਨ',
    'Breathing for Anxiety Relief': 'ਚਿੰਤਾ ਰਾਹਤ ਸਾਹ',
    'Low Impact Cardio Workout': 'ਘੱਟ ਪ੍ਰਭਾਵ ਕਾਰਡੀਓ ਵਰਕਆਉਟ',
    'Beginner HIIT Session': 'ਸ਼ੁਰੂਆਤੀ HIIT ਸੈਸ਼ਨ',
    'Full Body Stretch Routine': 'ਪੂਰੇ ਸਰੀਰ ਸਟ੍ਰੈਚ ਰੁਟੀਨ',
    '5-Minute Morning Stretch': '5-ਮਿੰਟ ਸਵੇਰ ਸਟ੍ਰੈਚ',
    '3 Healthy Breakfast Ideas': '3 ਸਿਹਤਮੰਦ ਨਾਸ਼ਤੇ ਦੇ ਵਿਚਾਰ',
    'Beginner Meal Prep Guide': 'ਸ਼ੁਰੂਆਤੀ ਭੋਜਨ ਤਿਆਰੀ ਗਾਈਡ',
  },
  te: {
    Yoga: 'యోగా',
    Meditation: 'ధ్యానం',
    Cardio: 'కార్డియో',
    Stretching: 'స్ట్రెచింగ్',
    'Healthy Diet': 'ఆరోగ్యకర ఆహారం',
    'Beginner Yoga Flow': 'ప్రారంభ యోగా ఫ్లో',
    'Yoga for Anxiety Relief': 'ఆందోళన ఉపశమన యోగా',
    'Bedtime Yoga': 'నిద్రకు ముందు యోగా',
    '5-Minute Daily Meditation': '5-నిమి దైనందిన ధ్యానం',
    'Sleep Meditation': 'నిద్ర ధ్యానం',
    'Anxiety-Calming Breath': 'ఆందోళన-శాంత శ్వాస',
    'Low Impact Cardio': 'తక్కువ ప్రభావ కార్డియో',
    'Beginner HIIT': 'ప్రారంభ HIIT',
    'Full Body Stretch': 'పూర్తి శరీర స్ట్రెచ్',
    'Morning Stretch': 'ఉదయం స్ట్రెచ్',
    'Healthy Breakfast Ideas': 'ఆరోగ్యకర అల్పాహార ఆలోచనలు',
    'Meal Prep Basics': 'భోజన తయారీ ప్రాథమికాలు',
    '10-Minute Beginner Yoga': '10-నిమి ప్రారంభ యోగా',
    'Gentle Morning Yoga': 'మృదువైన ఉదయం యోగా',
    'Yoga for Anxiety and Stress': 'ఆందోళన మరియు ఒత్తిడి యోగా',
    'Calming Yoga for Worry': 'ఆందోళనకు శాంత యోగా',
    'Bedtime Yoga for Relaxation': 'విశ్రాంతి నిద్ర యోగా',
    'Quick Reset Meditation': 'త్వరిత రీసెట్ ధ్యానం',
    'Deep Sleep Talk Down': 'లోతైన నిద్ర మార్గదర్శనం',
    'Breathing for Anxiety Relief': 'ఆందోళన ఉపశమన శ్వాస',
    'Low Impact Cardio Workout': 'తక్కువ ప్రభావ కార్డియో',
    'Beginner HIIT Session': 'ప్రారంభ HIIT సెషన్',
    'Full Body Stretch Routine': 'పూర్తి శరీర స్ట్రెచ్',
    '5-Minute Morning Stretch': '5-నిమి ఉదయం స్ట్రెచ్',
    '3 Healthy Breakfast Ideas': '3 ఆరోగ్యకర అల్పాహార ఆలోచనలు',
    'Beginner Meal Prep Guide': 'ప్రారంభ భోజన తయారీ గైడ్',
  },
  es: {
    Yoga: 'Yoga',
    Meditation: 'Meditación',
    Cardio: 'Cardio',
    Stretching: 'Estiramientos',
    'Healthy Diet': 'Dieta saludable',
    'Beginner Yoga Flow': 'Flujo de yoga para principiantes',
    'Yoga for Anxiety Relief': 'Yoga para aliviar la ansiedad',
    'Bedtime Yoga': 'Yoga antes de dormir',
    '5-Minute Daily Meditation': 'Meditación diaria de 5 minutos',
    'Sleep Meditation': 'Meditación para dormir',
    'Anxiety-Calming Breath': 'Respiración calmante para la ansiedad',
    'Low Impact Cardio': 'Cardio de bajo impacto',
    'Beginner HIIT': 'HIIT para principiantes',
    'Full Body Stretch': 'Estiramiento de cuerpo completo',
    'Morning Stretch': 'Estiramiento matutino',
    'Healthy Breakfast Ideas': 'Ideas de desayunos saludables',
    'Meal Prep Basics': 'Fundamentos de preparación de comidas',
    '10-Minute Beginner Yoga': 'Yoga para principiantes de 10 minutos',
    'Gentle Morning Yoga': 'Yoga matutino suave',
    'Yoga for Anxiety and Stress': 'Yoga para ansiedad y estrés',
    'Calming Yoga for Worry': 'Yoga calmante para la preocupación',
    'Bedtime Yoga for Relaxation': 'Yoga relajante antes de dormir',
    'Quick Reset Meditation': 'Meditación de reinicio rápido',
    'Deep Sleep Talk Down': 'Guía para dormir profundamente',
    'Breathing for Anxiety Relief': 'Respiración para aliviar la ansiedad',
    'Low Impact Cardio Workout': 'Entrenamiento cardio de bajo impacto',
    'Beginner HIIT Session': 'Sesión HIIT para principiantes',
    'Full Body Stretch Routine': 'Rutina de estiramiento completo',
    '5-Minute Morning Stretch': 'Estiramiento matutino de 5 minutos',
    '3 Healthy Breakfast Ideas': '3 ideas de desayunos saludables',
    'Beginner Meal Prep Guide': 'Guía de preparación de comidas para principiantes',
  },
};

const BN_FITNESS = {
  Yoga: 'যোগ',
  Meditation: 'ধ্যান',
  Cardio: 'কার্ডিও',
  Stretching: 'স্ট্রেচিং',
  'Healthy Diet': 'স্বাস্থ্যকর খাদ্য',
  'Beginner Yoga Flow': 'প্রাথমিক যোগ ফ্লো',
  'Yoga for Anxiety Relief': 'উদ্বেগ উপশম যোগ',
  'Bedtime Yoga': 'ঘুমানোর আগে যোগ',
  '5-Minute Daily Meditation': '৫-মিনিট দৈনিক ধ্যান',
  'Sleep Meditation': 'ঘুমের ধ্যান',
  'Anxiety-Calming Breath': 'উদ্বেগ-শান্ত শ্বাস',
  'Low Impact Cardio': 'কম প্রভাব কার্ডিও',
  'Beginner HIIT': 'প্রাথমিক HIIT',
  'Full Body Stretch': 'পুরো শরীরের স্ট্রেচ',
  'Morning Stretch': 'সকালের স্ট্রেচ',
  'Healthy Breakfast Ideas': 'স্বাস্থ্যকর নাশতার ধারণা',
  'Meal Prep Basics': 'খাবার প্রস্তুতির মূল বিষয়',
  '10-Minute Beginner Yoga': '১০-মিনিট প্রাথমিক যোগ',
  'Gentle Morning Yoga': 'মৃদু সকালের যোগ',
  'Yoga for Anxiety and Stress': 'উদ্বেগ ও চাপের যোগ',
  'Calming Yoga for Worry': 'চিন্তার জন্য শান্ত যোগ',
  'Bedtime Yoga for Relaxation': 'বিশ্রামের জন্য ঘুমানোর আগে যোগ',
  'Quick Reset Meditation': 'দ্রুত রিসেট ধ্যান',
  'Deep Sleep Talk Down': 'গভীর ঘুম গাইড',
  'Breathing for Anxiety Relief': 'উদ্বেগ উপশম শ্বাস',
  'Low Impact Cardio Workout': 'কম প্রভাব কার্ডিও ওয়ার্কআউট',
  'Beginner HIIT Session': 'প্রাথমিক HIIT সেশন',
  'Full Body Stretch Routine': 'পুরো শরীর স্ট্রেচ রুটিন',
  '5-Minute Morning Stretch': '৫-মিনিট সকালের স্ট্রেচ',
  '3 Healthy Breakfast Ideas': '৩টি স্বাস্থ্যকর নাশতার ধারণা',
  'Beginner Meal Prep Guide': 'প্রাথমিক খাবার প্রস্তুতি গাইড',
};

const TA_FITNESS = {
  Yoga: 'யோகா',
  Meditation: 'தியானம்',
  Cardio: 'கார்டியோ',
  Stretching: 'நீட்சி',
  'Healthy Diet': 'ஆரோக்கியமான உணவு',
  'Beginner Yoga Flow': 'தொடக்க யோகா ஓட்டம்',
  'Yoga for Anxiety Relief': 'கவலை தீர்க்கும் யோகா',
  'Bedtime Yoga': 'படுக்கைக்கு முன் யோகா',
  '5-Minute Daily Meditation': '5-நிமி தினசரி தியானம்',
  'Sleep Meditation': 'தூக்க தியானம்',
  'Anxiety-Calming Breath': 'கவலை-அமைதி சுவாசம்',
  'Low Impact Cardio': 'குறைந்த தாக்க கார்டியோ',
  'Beginner HIIT': 'தொடக்க HIIT',
  'Full Body Stretch': 'முழு உடல் நீட்சி',
  'Morning Stretch': 'காலை நீட்சி',
  'Healthy Breakfast Ideas': 'ஆரோக்கிய காலை உணவு யோசனைகள்',
  'Meal Prep Basics': 'உணவு தயாரிப்பு அடிப்படை',
  '10-Minute Beginner Yoga': '10-நிமி தொடக்க யோகா',
  'Gentle Morning Yoga': 'மென்மையான காலை யோகா',
  'Yoga for Anxiety and Stress': 'கவலை மற்றும் மன அழுத்த யோகா',
  'Calming Yoga for Worry': 'கவலைக்கான அமைதி யோகா',
  'Bedtime Yoga for Relaxation': 'ஓய்வுக்கான படுக்கை யோகா',
  'Quick Reset Meditation': 'விரைவு மீட்டமை தியானம்',
  'Deep Sleep Talk Down': 'ஆழ்ந்த தூக்க வழிகாட்டல்',
  'Breathing for Anxiety Relief': 'கவலை தீர்க்கும் சுவாசம்',
  'Low Impact Cardio Workout': 'குறைந்த தாக்க கார்டியோ',
  'Beginner HIIT Session': 'தொடக்க HIIT அமர்வு',
  'Full Body Stretch Routine': 'முழு உடல் நீட்சி',
  '5-Minute Morning Stretch': '5-நிமி காலை நீட்சி',
  '3 Healthy Breakfast Ideas': '3 ஆரோக்கிய காலை உணவு யோசனைகள்',
  'Beginner Meal Prep Guide': 'தொடக்க உணவு தயாரிப்பு வழிகாட்டி',
};

const GU_FITNESS = {
  Yoga: 'યોગ',
  Meditation: 'ધ્યાન',
  Cardio: 'કાર્ડિયો',
  Stretching: 'સ્ટ્રેચિંગ',
  'Healthy Diet': 'સ્વસ્થ આહાર',
  'Beginner Yoga Flow': 'શરૂઆતી યોગ ફ્લો',
  'Yoga for Anxiety Relief': 'ચિંતા રાહત યોગ',
  'Bedtime Yoga': 'સૂવાના પહેલાં યોગ',
  '5-Minute Daily Meditation': '5-મિનિટ દૈનિક ધ્યાન',
  'Sleep Meditation': 'નિદ્રા ધ્યાન',
  'Anxiety-Calming Breath': 'ચિંતા-શાંત શ્વાસ',
  'Low Impact Cardio': 'ઓછી અસર કાર્ડિયો',
  'Beginner HIIT': 'શરૂઆતી HIIT',
  'Full Body Stretch': 'સંપૂર્ણ શરીર સ્ટ્રેચ',
  'Morning Stretch': 'સવારની સ્ટ્રેચ',
  'Healthy Breakfast Ideas': 'સ્વસ્થ નાસ્તાના વિચારો',
  'Meal Prep Basics': 'ભોજન તૈયારીની મૂળભૂત બાબતો',
  '10-Minute Beginner Yoga': '10-મિનિટ શરૂઆતી યોગ',
  'Gentle Morning Yoga': 'હળવો સવાર યોગ',
  'Yoga for Anxiety and Stress': 'ચિંતા અને તણાવ માટે યોગ',
  'Calming Yoga for Worry': 'ચિંતા માટે શાંત યોગ',
  'Bedtime Yoga for Relaxation': 'આરામ માટે સૂવાનો યોગ',
  'Quick Reset Meditation': 'ઝડપી રીસેટ ધ્યાન',
  'Deep Sleep Talk Down': 'ઊંડી નિદ્રા માર્ગદર્શન',
  'Breathing for Anxiety Relief': 'ચિંતા રાહત શ્વાસ',
  'Low Impact Cardio Workout': 'ઓછી અસર કાર્ડિયો વર્કઆઉટ',
  'Beginner HIIT Session': 'શરૂઆતી HIIT સત્ર',
  'Full Body Stretch Routine': 'સંપૂર્ણ શરીર સ્ટ્રેચ',
  '5-Minute Morning Stretch': '5-મિનિટ સવાર સ્ટ્રેચ',
  '3 Healthy Breakfast Ideas': '3 સ્વસ્થ નાસ્તાના વિચારો',
  'Beginner Meal Prep Guide': 'શરૂઆતી ભોજન તૈયારી માર્ગદર્શિકા',
};

const KN_FITNESS = {
  Yoga: 'ಯೋಗ',
  Meditation: 'ಧ್ಯಾನ',
  Cardio: 'ಕಾರ್ಡಿಯೋ',
  Stretching: 'ಸ್ಟ್ರೆಚಿಂಗ್',
  'Healthy Diet': 'ಆರೋಗ್ಯಕರ ಆಹಾರ',
  'Beginner Yoga Flow': 'ಆರಂಭಿಕ ಯೋಗ ಫ್ಲೋ',
  'Yoga for Anxiety Relief': 'ಆತಂಕ ನಿವಾರಣೆ ಯೋಗ',
  'Bedtime Yoga': 'ಮಲಗುವ ಮೊದಲು ಯೋಗ',
  '5-Minute Daily Meditation': '5-ನಿಮಿ ದೈನಂದಿನ ಧ್ಯಾನ',
  'Sleep Meditation': 'ನಿದ್ರಾ ಧ್ಯಾನ',
  'Anxiety-Calming Breath': 'ಆತಂಕ-ಶಾಂತ ಉಸಿರಾಟ',
  'Low Impact Cardio': 'ಕಡಿಮೆ ಪ್ರಭಾವ ಕಾರ್ಡಿಯೋ',
  'Beginner HIIT': 'ಆರಂಭಿಕ HIIT',
  'Full Body Stretch': 'ಪೂರ್ಣ ಶರೀರ ಸ್ಟ್ರೆಚ್',
  'Morning Stretch': 'ಬೆಳಗಿನ ಸ್ಟ್ರೆಚ್',
  'Healthy Breakfast Ideas': 'ಆರೋಗ್ಯಕರ ಉಪಾಹಾರ ಆಲೋಚನೆಗಳು',
  'Meal Prep Basics': 'ಊಟ ತಯಾರಿ ಮೂಲಭೂತಗಳು',
  '10-Minute Beginner Yoga': '10-ನಿಮಿ ಆರಂಭಿಕ ಯೋಗ',
  'Gentle Morning Yoga': 'ಮೃದು ಬೆಳಗಿನ ಯೋಗ',
  'Yoga for Anxiety and Stress': 'ಆತಂಕ ಮತ್ತು ಒತ್ತಡ ಯೋಗ',
  'Calming Yoga for Worry': 'ಚಿಂತೆಗೆ ಶಾಂತ ಯೋಗ',
  'Bedtime Yoga for Relaxation': 'ವಿಶ್ರಾಂತಿ ಮಲಗುವ ಯೋಗ',
  'Quick Reset Meditation': 'ತ್ವರಿತ ರೀಸೆಟ್ ಧ್ಯಾನ',
  'Deep Sleep Talk Down': 'ಆಳವಾದ ನಿದ್ರೆ ಮಾರ್ಗದರ್ಶನ',
  'Breathing for Anxiety Relief': 'ಆತಂಕ ನಿವಾರಣೆ ಉಸಿರಾಟ',
  'Low Impact Cardio Workout': 'ಕಡಿಮೆ ಪ್ರಭಾವ ಕಾರ್ಡಿಯೋ',
  'Beginner HIIT Session': 'ಆರಂಭಿಕ HIIT ಅವಧಿ',
  'Full Body Stretch Routine': 'ಪೂರ್ಣ ಶರೀರ ಸ್ಟ್ರೆಚ್',
  '5-Minute Morning Stretch': '5-ನಿಮಿ ಬೆಳಗಿನ ಸ್ಟ್ರೆಚ್',
  '3 Healthy Breakfast Ideas': '3 ಆರೋಗ್ಯಕರ ಉಪಾಹಾರ ಆಲೋಚನೆಗಳು',
  'Beginner Meal Prep Guide': 'ಆರಂಭಿಕ ಊಟ ತಯಾರಿ ಮಾರ್ಗದರ್ಶಿ',
};

const ML_FITNESS = {
  Yoga: 'യോഗ',
  Meditation: 'ധ്യാനം',
  Cardio: 'കാർഡിയോ',
  Stretching: 'സ്ട്രെച്ചിംഗ്',
  'Healthy Diet': 'ആരോഗ്യകരമായ ഭക്ഷണം',
  'Beginner Yoga Flow': 'ആരംഭക യോഗ ഫ്ലോ',
  'Yoga for Anxiety Relief': 'ആശങ്കയ്ക്ക് യോഗ',
  'Bedtime Yoga': 'ഉറങ്ങുന്നതിന് മുമ്പ് യോഗ',
  '5-Minute Daily Meditation': '5-മിനിറ്റ് ദൈനംധ്യാനം',
  'Sleep Meditation': 'ഉറക്ക ധ്യാനം',
  'Anxiety-Calming Breath': 'ആശങ്ക-ശാന്ത ശ്വാസം',
  'Low Impact Cardio': 'കുറഞ്ഞ പ്രഭാവ കാർഡിയോ',
  'Beginner HIIT': 'ആരംഭക HIIT',
  'Full Body Stretch': 'പൂർണ്ണ ശരീര സ്ട്രെച്ച്',
  'Morning Stretch': 'പ്രഭാത സ്ട്രെച്ച്',
  'Healthy Breakfast Ideas': 'ആരോഗ്യകരമായ പ്രഭാത ഭക്ഷണ ആശയങ്ങൾ',
  'Meal Prep Basics': 'ഭക്ഷണ തയ്യാറിന്റെ അടിസ്ഥാനങ്ങൾ',
  '10-Minute Beginner Yoga': '10-മിനിറ്റ് ആരംഭക യോഗ',
  'Gentle Morning Yoga': 'മൃദുവായ പ്രഭാത യോഗ',
  'Yoga for Anxiety and Stress': 'ആശങ്കയും സമ്മർദ്ദവും യോഗ',
  'Calming Yoga for Worry': 'കവലയ്ക്ക് ശാന്ത യോഗ',
  'Bedtime Yoga for Relaxation': 'വിശ്രമത്തിനുള്ള യോഗ',
  'Quick Reset Meditation': 'ദ്രുത റീസെറ്റ് ധ്യാനം',
  'Deep Sleep Talk Down': 'ആഴത്തിലുള്ള ഉറക്ക മാർഗ്ഗനിർദേശം',
  'Breathing for Anxiety Relief': 'ആശങ്കയ്ക്കുള്ള ശ്വാസം',
  'Low Impact Cardio Workout': 'കുറഞ്ഞ പ്രഭാവ കാർഡിയോ',
  'Beginner HIIT Session': 'ആരംഭക HIIT സെഷൻ',
  'Full Body Stretch Routine': 'പൂർണ്ണ ശരീര സ്ട്രെച്ച്',
  '5-Minute Morning Stretch': '5-മിനിറ്റ് പ്രഭാത സ്ട്രെച്ച്',
  '3 Healthy Breakfast Ideas': '3 ആരോഗ്യകരമായ പ്രഭാത ഭക്ഷണ ആശയങ്ങൾ',
  'Beginner Meal Prep Guide': 'ആരംഭക ഭക്ഷണ തയ്യാറ് ഗൈഡ്',
};

FITNESS_LABELS.mr = { ...FITNESS_LABELS.hi };
FITNESS_LABELS.bn = BN_FITNESS;
FITNESS_LABELS.ta = TA_FITNESS;
FITNESS_LABELS.gu = GU_FITNESS;
FITNESS_LABELS.kn = KN_FITNESS;
FITNESS_LABELS.ml = ML_FITNESS;
for (const lang of ['fr', 'de', 'pt', 'ar', 'zh']) {
  FITNESS_LABELS[lang] = { ...FITNESS_LABELS.es };
}

function getFitnessLabelFallback(text, language) {
  const lang = normalizeLanguage(language);
  if (lang === 'en' || !text) return text;
  const pack = FITNESS_LABELS[lang] || FITNESS_LABELS.hi;
  return pack[text] || FITNESS_LABELS_EN[text] || text;
}

function applyFitnessLabelFallbacks(labels, language) {
  const lang = normalizeLanguage(language);
  if (lang === 'en' || !labels?.length) return labels;
  return labels.map((label) => getFitnessLabelFallback(label, lang));
}

module.exports = {
  FITNESS_LABELS_EN,
  FITNESS_LABELS,
  getFitnessLabelFallback,
  applyFitnessLabelFallbacks,
};
